// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXomZlbvFa0JkQuLLJEf28pzchdvWc5Pg',
    appId: '1:142784337112:web:96159b0332283da9d273ad',
    messagingSenderId: '142784337112',
    projectId: 'mitic-8cddc',
    authDomain: 'mitic-8cddc.firebaseapp.com',
    databaseURL: 'https://mitic-8cddc-default-rtdb.firebaseio.com',
    storageBucket: 'mitic-8cddc.firebasestorage.app',
    measurementId: 'G-5LPHPP7KHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDmHoEsKTgKXSk5Uyd2qa0sOaaEo1WPtQ',
    appId: '1:142784337112:android:6bf5f3f9a2ead635d273ad',
    messagingSenderId: '142784337112',
    projectId: 'mitic-8cddc',
    databaseURL: 'https://mitic-8cddc-default-rtdb.firebaseio.com',
    storageBucket: 'mitic-8cddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCEWZdc-LK0M8-m8YmIox8ouGFdfIoYSg',
    appId: '1:142784337112:ios:e9d70c61776dbd3bd273ad',
    messagingSenderId: '142784337112',
    projectId: 'mitic-8cddc',
    databaseURL: 'https://mitic-8cddc-default-rtdb.firebaseio.com',
    storageBucket: 'mitic-8cddc.firebasestorage.app',
    iosBundleId: 'com.example.mitic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCEWZdc-LK0M8-m8YmIox8ouGFdfIoYSg',
    appId: '1:142784337112:ios:e9d70c61776dbd3bd273ad',
    messagingSenderId: '142784337112',
    projectId: 'mitic-8cddc',
    databaseURL: 'https://mitic-8cddc-default-rtdb.firebaseio.com',
    storageBucket: 'mitic-8cddc.firebasestorage.app',
    iosBundleId: 'com.example.mitic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXomZlbvFa0JkQuLLJEf28pzchdvWc5Pg',
    appId: '1:142784337112:web:a04588fdaa3103ced273ad',
    messagingSenderId: '142784337112',
    projectId: 'mitic-8cddc',
    authDomain: 'mitic-8cddc.firebaseapp.com',
    databaseURL: 'https://mitic-8cddc-default-rtdb.firebaseio.com',
    storageBucket: 'mitic-8cddc.firebasestorage.app',
    measurementId: 'G-SMJC2LD56D',
  );
}
